version: "3.9"

services:
  notion:
    image: lifefilm/loconotion
    volumes:
      - ./dist:/app/loconotion/dist
      - ./front/landing:/app/loconotion/front/landing
    restart: always
    command: front/landing/bashair.toml
